# coding: utf-8

"""
    SUPLA Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.client_apps_api import ClientAppsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestClientAppsApi(unittest.TestCase):
    """ClientAppsApi unit test stubs"""

    def setUp(self):
        self.api = api.client_apps_api.ClientAppsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_client_app(self):
        """Test case for delete_client_app

        Delete Client App  # noqa: E501
        """
        pass

    def test_get_client_apps(self):
        """Test case for get_client_apps

        Get client apps  # noqa: E501
        """
        pass

    def test_update_client_app(self):
        """Test case for update_client_app

        Update client app  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
