# coding: utf-8

"""
    SUPLA Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.channel_groups_api import ChannelGroupsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestChannelGroupsApi(unittest.TestCase):
    """ChannelGroupsApi unit test stubs"""

    def setUp(self):
        self.api = api.channel_groups_api.ChannelGroupsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_channel_group(self):
        """Test case for create_channel_group

        Create a new channel group  # noqa: E501
        """
        pass

    def test_delete_channel_group(self):
        """Test case for delete_channel_group

        Delete Channel Group  # noqa: E501
        """
        pass

    def test_execute_channel_group_action(self):
        """Test case for execute_channel_group_action

        Execute action on the channel group  # noqa: E501
        """
        pass

    def test_get_channel_group(self):
        """Test case for get_channel_group

        Get channel group by ID  # noqa: E501
        """
        pass

    def test_get_channel_groups(self):
        """Test case for get_channel_groups

        Get channels list  # noqa: E501
        """
        pass

    def test_update_channel_group(self):
        """Test case for update_channel_group

        Update channel group  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
