# coding: utf-8

"""
    SUPLA Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.direct_links_api import DirectLinksApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDirectLinksApi(unittest.TestCase):
    """DirectLinksApi unit test stubs"""

    def setUp(self):
        self.api = api.direct_links_api.DirectLinksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_direct_link(self):
        """Test case for create_direct_link

        Create a new Direct Link  # noqa: E501
        """
        pass

    def test_delete_direct_link(self):
        """Test case for delete_direct_link

        Delete Direct Link  # noqa: E501
        """
        pass

    def test_get_direct_link(self):
        """Test case for get_direct_link

        Get Direct Link  # noqa: E501
        """
        pass

    def test_get_direct_link_audit(self):
        """Test case for get_direct_link_audit

        Get Direct Link audit  # noqa: E501
        """
        pass

    def test_get_direct_links(self):
        """Test case for get_direct_links

        Get Direct Links list  # noqa: E501
        """
        pass

    def test_update_direct_link(self):
        """Test case for update_direct_link

        Update Direct Link  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
