# coding: utf-8

"""
    SUPLA Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.brightness_state import BrightnessState  # noqa: E501
from swagger_client.rest import ApiException


class TestBrightnessState(unittest.TestCase):
    """BrightnessState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBrightnessState(self):
        """Test BrightnessState"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.brightness_state.BrightnessState()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
