# coding: utf-8

"""
    SUPLA Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.partial_open_state import PartialOpenState  # noqa: E501
from swagger_client.rest import ApiException


class TestPartialOpenState(unittest.TestCase):
    """PartialOpenState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPartialOpenState(self):
        """Test PartialOpenState"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.partial_open_state.PartialOpenState()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
