# coding: utf-8

"""
    SUPLA Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.users_api import UsersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = api.users_api.UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_current_user(self):
        """Test case for get_current_user

        Get current user  # noqa: E501
        """
        pass

    def test_update_current_user(self):
        """Test case for update_current_user

        Update current user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
