# coding: utf-8

"""
    SUPLA Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.access_identifiers_api import AccessIdentifiersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAccessIdentifiersApi(unittest.TestCase):
    """AccessIdentifiersApi unit test stubs"""

    def setUp(self):
        self.api = api.access_identifiers_api.AccessIdentifiersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_access_identifier(self):
        """Test case for create_access_identifier

        Create a new Access Identifier  # noqa: E501
        """
        pass

    def test_delete_access_identifier(self):
        """Test case for delete_access_identifier

        Delete Access Identifier  # noqa: E501
        """
        pass

    def test_get_access_identifier(self):
        """Test case for get_access_identifier

        Get Access Identifier  # noqa: E501
        """
        pass

    def test_get_access_identifiers(self):
        """Test case for get_access_identifiers

        Get Access Identifiers list  # noqa: E501
        """
        pass

    def test_update_access_identifier(self):
        """Test case for update_access_identifier

        Update Access Identifier  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
