# coding: utf-8

"""
    SUPLA Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.schedules_api import SchedulesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSchedulesApi(unittest.TestCase):
    """SchedulesApi unit test stubs"""

    def setUp(self):
        self.api = api.schedules_api.SchedulesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_schedule(self):
        """Test case for create_schedule

        Create a new schedule  # noqa: E501
        """
        pass

    def test_delete_schedule(self):
        """Test case for delete_schedule

        Delete Schedule  # noqa: E501
        """
        pass

    def test_enable_schedules(self):
        """Test case for enable_schedules

        Enable schedules  # noqa: E501
        """
        pass

    def test_get_schedule(self):
        """Test case for get_schedule

        Get Schedule  # noqa: E501
        """
        pass

    def test_get_schedules(self):
        """Test case for get_schedules

        Get schedules list  # noqa: E501
        """
        pass

    def test_update_schedule(self):
        """Test case for update_schedule

        Update schedule  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
