# coding: utf-8

"""
    SUPLA Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.channels_api import ChannelsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestChannelsApi(unittest.TestCase):
    """ChannelsApi unit test stubs"""

    def setUp(self):
        self.api = api.channels_api.ChannelsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_execute_action(self):
        """Test case for execute_action

        Execute action on the channel  # noqa: E501
        """
        pass

    def test_get_channel(self):
        """Test case for get_channel

        Get channel by ID  # noqa: E501
        """
        pass

    def test_get_channel_measurement_logs(self):
        """Test case for get_channel_measurement_logs

        Get measurement logs.  # noqa: E501
        """
        pass

    def test_get_channel_measurement_logs_csv_file(self):
        """Test case for get_channel_measurement_logs_csv_file

        Get measurement logs as zipped CSV file.  # noqa: E501
        """
        pass

    def test_get_channel_schedules(self):
        """Test case for get_channel_schedules

        Get schedules list of the channel  # noqa: E501
        """
        pass

    def test_get_channels(self):
        """Test case for get_channels

        Get channels list  # noqa: E501
        """
        pass

    def test_update_channel(self):
        """Test case for update_channel

        Update channel  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
