# coding: utf-8

"""
    SUPLA Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.color_state import ColorState  # noqa: E501
from swagger_client.rest import ApiException


class TestColorState(unittest.TestCase):
    """ColorState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testColorState(self):
        """Test ColorState"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.color_state.ColorState()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
