# coding: utf-8

"""
    SUPLA Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.io_device_update_request import IODeviceUpdateRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestIODeviceUpdateRequest(unittest.TestCase):
    """IODeviceUpdateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIODeviceUpdateRequest(self):
        """Test IODeviceUpdateRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.io_device_update_request.IODeviceUpdateRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
