# coding: utf-8

"""
    SUPLA Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.channel_function_enum_names import ChannelFunctionEnumNames  # noqa: E501
from swagger_client.rest import ApiException


class TestChannelFunctionEnumNames(unittest.TestCase):
    """ChannelFunctionEnumNames unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChannelFunctionEnumNames(self):
        """Test ChannelFunctionEnumNames"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.channel_function_enum_names.ChannelFunctionEnumNames()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
