# coding: utf-8

"""
    SUPLA Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.io_devices_api import IODevicesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestIODevicesApi(unittest.TestCase):
    """IODevicesApi unit test stubs"""

    def setUp(self):
        self.api = api.io_devices_api.IODevicesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_io_device(self):
        """Test case for delete_io_device

        Delete IO Device  # noqa: E501
        """
        pass

    def test_get_io_device(self):
        """Test case for get_io_device

        Get IO Device  # noqa: E501
        """
        pass

    def test_get_io_device_channels(self):
        """Test case for get_io_device_channels

        Get Channels that belong to IO Device  # noqa: E501
        """
        pass

    def test_get_io_devices(self):
        """Test case for get_io_devices

        Get IO Devices  # noqa: E501
        """
        pass

    def test_update_io_device(self):
        """Test case for update_io_device

        Update IO Device  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
