# coding: utf-8

"""
    SUPLA Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.locations_api import LocationsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestLocationsApi(unittest.TestCase):
    """LocationsApi unit test stubs"""

    def setUp(self):
        self.api = api.locations_api.LocationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_location(self):
        """Test case for create_location

        Create a new location  # noqa: E501
        """
        pass

    def test_delete_location(self):
        """Test case for delete_location

        Delete location  # noqa: E501
        """
        pass

    def test_get_location(self):
        """Test case for get_location

        Get location by ID  # noqa: E501
        """
        pass

    def test_get_locations(self):
        """Test case for get_locations

        Get locations list  # noqa: E501
        """
        pass

    def test_update_location(self):
        """Test case for update_location

        Update location  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
