# coding: utf-8

"""
    SUPLA Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.user_icons_api import UserIconsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUserIconsApi(unittest.TestCase):
    """UserIconsApi unit test stubs"""

    def setUp(self):
        self.api = api.user_icons_api.UserIconsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_user_icon(self):
        """Test case for create_user_icon

        Create a new User Icon  # noqa: E501
        """
        pass

    def test_delete_user_icon(self):
        """Test case for delete_user_icon

        Delete User Icon  # noqa: E501
        """
        pass

    def test_get_user_icons(self):
        """Test case for get_user_icons

        Get user icons  # noqa: E501
        """
        pass

    def test_user_icons_id_image_index_get(self):
        """Test case for user_icons_id_image_index_get

        Get User Icon image at specified index  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
