# coding: utf-8

"""
    SUPLA Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.server_api import ServerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestServerApi(unittest.TestCase):
    """ServerApi unit test stubs"""

    def setUp(self):
        self.api = api.server_api.ServerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_server_info(self):
        """Test case for get_server_info

        Get server info  # noqa: E501
        """
        pass

    def test_get_supla_server_status(self):
        """Test case for get_supla_server_status

        Get the SUPLA Server status  # noqa: E501
        """
        pass

    def test_get_token_info(self):
        """Test case for get_token_info

        Returns information about used access token  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
