# coding: utf-8

"""
    SUPLA Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.client_app import ClientApp  # noqa: E501
from swagger_client.rest import ApiException


class TestClientApp(unittest.TestCase):
    """ClientApp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClientApp(self):
        """Test ClientApp"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.client_app.ClientApp()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
