# coding: utf-8

"""
    SUPLA Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.distance_state import DistanceState  # noqa: E501
from swagger_client.rest import ApiException


class TestDistanceState(unittest.TestCase):
    """DistanceState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDistanceState(self):
        """Test DistanceState"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.distance_state.DistanceState()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
