# coding: utf-8

"""
    SUPLA Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ChannelGroupRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'caption': 'str',
        'alt_icon': 'int',
        'user_icon_id': 'int',
        'hidden': 'bool',
        'location_id': 'int',
        'channel_ids': 'list[int]'
    }

    attribute_map = {
        'caption': 'caption',
        'alt_icon': 'altIcon',
        'user_icon_id': 'userIconId',
        'hidden': 'hidden',
        'location_id': 'locationId',
        'channel_ids': 'channelIds'
    }

    def __init__(self, caption=None, alt_icon=None, user_icon_id=None, hidden=None, location_id=None, channel_ids=None):  # noqa: E501
        """ChannelGroupRequest - a model defined in Swagger"""  # noqa: E501
        self._caption = None
        self._alt_icon = None
        self._user_icon_id = None
        self._hidden = None
        self._location_id = None
        self._channel_ids = None
        self.discriminator = None
        if caption is not None:
            self.caption = caption
        if alt_icon is not None:
            self.alt_icon = alt_icon
        if user_icon_id is not None:
            self.user_icon_id = user_icon_id
        if hidden is not None:
            self.hidden = hidden
        if location_id is not None:
            self.location_id = location_id
        self.channel_ids = channel_ids

    @property
    def caption(self):
        """Gets the caption of this ChannelGroupRequest.  # noqa: E501


        :return: The caption of this ChannelGroupRequest.  # noqa: E501
        :rtype: str
        """
        return self._caption

    @caption.setter
    def caption(self, caption):
        """Sets the caption of this ChannelGroupRequest.


        :param caption: The caption of this ChannelGroupRequest.  # noqa: E501
        :type: str
        """

        self._caption = caption

    @property
    def alt_icon(self):
        """Gets the alt_icon of this ChannelGroupRequest.  # noqa: E501


        :return: The alt_icon of this ChannelGroupRequest.  # noqa: E501
        :rtype: int
        """
        return self._alt_icon

    @alt_icon.setter
    def alt_icon(self, alt_icon):
        """Sets the alt_icon of this ChannelGroupRequest.


        :param alt_icon: The alt_icon of this ChannelGroupRequest.  # noqa: E501
        :type: int
        """

        self._alt_icon = alt_icon

    @property
    def user_icon_id(self):
        """Gets the user_icon_id of this ChannelGroupRequest.  # noqa: E501


        :return: The user_icon_id of this ChannelGroupRequest.  # noqa: E501
        :rtype: int
        """
        return self._user_icon_id

    @user_icon_id.setter
    def user_icon_id(self, user_icon_id):
        """Sets the user_icon_id of this ChannelGroupRequest.


        :param user_icon_id: The user_icon_id of this ChannelGroupRequest.  # noqa: E501
        :type: int
        """

        self._user_icon_id = user_icon_id

    @property
    def hidden(self):
        """Gets the hidden of this ChannelGroupRequest.  # noqa: E501


        :return: The hidden of this ChannelGroupRequest.  # noqa: E501
        :rtype: bool
        """
        return self._hidden

    @hidden.setter
    def hidden(self, hidden):
        """Sets the hidden of this ChannelGroupRequest.


        :param hidden: The hidden of this ChannelGroupRequest.  # noqa: E501
        :type: bool
        """

        self._hidden = hidden

    @property
    def location_id(self):
        """Gets the location_id of this ChannelGroupRequest.  # noqa: E501


        :return: The location_id of this ChannelGroupRequest.  # noqa: E501
        :rtype: int
        """
        return self._location_id

    @location_id.setter
    def location_id(self, location_id):
        """Sets the location_id of this ChannelGroupRequest.


        :param location_id: The location_id of this ChannelGroupRequest.  # noqa: E501
        :type: int
        """

        self._location_id = location_id

    @property
    def channel_ids(self):
        """Gets the channel_ids of this ChannelGroupRequest.  # noqa: E501


        :return: The channel_ids of this ChannelGroupRequest.  # noqa: E501
        :rtype: list[int]
        """
        return self._channel_ids

    @channel_ids.setter
    def channel_ids(self, channel_ids):
        """Sets the channel_ids of this ChannelGroupRequest.


        :param channel_ids: The channel_ids of this ChannelGroupRequest.  # noqa: E501
        :type: list[int]
        """
        if channel_ids is None:
            raise ValueError("Invalid value for `channel_ids`, must not be `None`")  # noqa: E501

        self._channel_ids = channel_ids

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ChannelGroupRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ChannelGroupRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
