# coding: utf-8

"""
    SUPLA Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ChannelFunctionEnumNames(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    NONE = "NONE"
    CONTROLLINGTHEGATEWAYLOCK = "CONTROLLINGTHEGATEWAYLOCK"
    CONTROLLINGTHEGATE = "CONTROLLINGTHEGATE"
    CONTROLLINGTHEGARAGEDOOR = "CONTROLLINGTHEGARAGEDOOR"
    THERMOMETER = "THERMOMETER"
    HUMIDITY = "HUMIDITY"
    HUMIDITYANDTEMPERATURE = "HUMIDITYANDTEMPERATURE"
    OPENINGSENSOR_GATEWAY = "OPENINGSENSOR_GATEWAY"
    OPENINGSENSOR_GATE = "OPENINGSENSOR_GATE"
    OPENINGSENSOR_GARAGEDOOR = "OPENINGSENSOR_GARAGEDOOR"
    NOLIQUIDSENSOR = "NOLIQUIDSENSOR"
    CONTROLLINGTHEDOORLOCK = "CONTROLLINGTHEDOORLOCK"
    OPENINGSENSOR_DOOR = "OPENINGSENSOR_DOOR"
    CONTROLLINGTHEROLLERSHUTTER = "CONTROLLINGTHEROLLERSHUTTER"
    OPENINGSENSOR_ROLLERSHUTTER = "OPENINGSENSOR_ROLLERSHUTTER"
    POWERSWITCH = "POWERSWITCH"
    LIGHTSWITCH = "LIGHTSWITCH"
    DIMMER = "DIMMER"
    RGBLIGHTING = "RGBLIGHTING"
    DIMMERANDRGBLIGHTING = "DIMMERANDRGBLIGHTING"
    DEPTHSENSOR = "DEPTHSENSOR"
    DISTANCESENSOR = "DISTANCESENSOR"
    OPENINGSENSOR_WINDOW = "OPENINGSENSOR_WINDOW"
    MAILSENSOR = "MAILSENSOR"
    WINDSENSOR = "WINDSENSOR"
    PRESSURESENSOR = "PRESSURESENSOR"
    RAINSENSOR = "RAINSENSOR"
    WEIGHTSENSOR = "WEIGHTSENSOR"
    WEATHER_STATION = "WEATHER_STATION"
    STAIRCASETIMER = "STAIRCASETIMER"
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
    }

    attribute_map = {
    }

    def __init__(self):  # noqa: E501
        """ChannelFunctionEnumNames - a model defined in Swagger"""  # noqa: E501
        self.discriminator = None

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ChannelFunctionEnumNames, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ChannelFunctionEnumNames):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
