# coding: utf-8

"""
    SUPLA Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ClientAppUpdateRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'caption': 'str',
        'enabled': 'bool',
        'access_id_id': 'int'
    }

    attribute_map = {
        'caption': 'caption',
        'enabled': 'enabled',
        'access_id_id': 'accessIdId'
    }

    def __init__(self, caption=None, enabled=None, access_id_id=None):  # noqa: E501
        """ClientAppUpdateRequest - a model defined in Swagger"""  # noqa: E501
        self._caption = None
        self._enabled = None
        self._access_id_id = None
        self.discriminator = None
        if caption is not None:
            self.caption = caption
        if enabled is not None:
            self.enabled = enabled
        if access_id_id is not None:
            self.access_id_id = access_id_id

    @property
    def caption(self):
        """Gets the caption of this ClientAppUpdateRequest.  # noqa: E501


        :return: The caption of this ClientAppUpdateRequest.  # noqa: E501
        :rtype: str
        """
        return self._caption

    @caption.setter
    def caption(self, caption):
        """Sets the caption of this ClientAppUpdateRequest.


        :param caption: The caption of this ClientAppUpdateRequest.  # noqa: E501
        :type: str
        """

        self._caption = caption

    @property
    def enabled(self):
        """Gets the enabled of this ClientAppUpdateRequest.  # noqa: E501


        :return: The enabled of this ClientAppUpdateRequest.  # noqa: E501
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """Sets the enabled of this ClientAppUpdateRequest.


        :param enabled: The enabled of this ClientAppUpdateRequest.  # noqa: E501
        :type: bool
        """

        self._enabled = enabled

    @property
    def access_id_id(self):
        """Gets the access_id_id of this ClientAppUpdateRequest.  # noqa: E501


        :return: The access_id_id of this ClientAppUpdateRequest.  # noqa: E501
        :rtype: int
        """
        return self._access_id_id

    @access_id_id.setter
    def access_id_id(self, access_id_id):
        """Sets the access_id_id of this ClientAppUpdateRequest.


        :param access_id_id: The access_id_id of this ClientAppUpdateRequest.  # noqa: E501
        :type: int
        """

        self._access_id_id = access_id_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ClientAppUpdateRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ClientAppUpdateRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
