# coding: utf-8

"""
    SUPLA Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from swagger_client.models.actionable_subject_type_enum import ActionableSubjectTypeEnum  # noqa: F401,E501
from swagger_client.models.channel_function_action_enum import ChannelFunctionActionEnum  # noqa: F401,E501
from swagger_client.models.direct_link_active_date_range import DirectLinkActiveDateRange  # noqa: F401,E501


class DirectLinkRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'subject_id': 'int',
        'subject_type': 'ActionableSubjectTypeEnum',
        'allowed_actions': 'list[ChannelFunctionActionEnum]',
        'active_date_range': 'DirectLinkActiveDateRange',
        'executions_limit': 'int',
        'caption': 'str',
        'enabled': 'bool',
        'disable_http_get': 'bool'
    }

    attribute_map = {
        'subject_id': 'subjectId',
        'subject_type': 'subjectType',
        'allowed_actions': 'allowedActions',
        'active_date_range': 'activeDateRange',
        'executions_limit': 'executionsLimit',
        'caption': 'caption',
        'enabled': 'enabled',
        'disable_http_get': 'disableHttpGet'
    }

    def __init__(self, subject_id=None, subject_type=None, allowed_actions=None, active_date_range=None, executions_limit=None, caption=None, enabled=None, disable_http_get=None):  # noqa: E501
        """DirectLinkRequest - a model defined in Swagger"""  # noqa: E501
        self._subject_id = None
        self._subject_type = None
        self._allowed_actions = None
        self._active_date_range = None
        self._executions_limit = None
        self._caption = None
        self._enabled = None
        self._disable_http_get = None
        self.discriminator = None
        if subject_id is not None:
            self.subject_id = subject_id
        if subject_type is not None:
            self.subject_type = subject_type
        if allowed_actions is not None:
            self.allowed_actions = allowed_actions
        if active_date_range is not None:
            self.active_date_range = active_date_range
        if executions_limit is not None:
            self.executions_limit = executions_limit
        if caption is not None:
            self.caption = caption
        if enabled is not None:
            self.enabled = enabled
        if disable_http_get is not None:
            self.disable_http_get = disable_http_get

    @property
    def subject_id(self):
        """Gets the subject_id of this DirectLinkRequest.  # noqa: E501


        :return: The subject_id of this DirectLinkRequest.  # noqa: E501
        :rtype: int
        """
        return self._subject_id

    @subject_id.setter
    def subject_id(self, subject_id):
        """Sets the subject_id of this DirectLinkRequest.


        :param subject_id: The subject_id of this DirectLinkRequest.  # noqa: E501
        :type: int
        """

        self._subject_id = subject_id

    @property
    def subject_type(self):
        """Gets the subject_type of this DirectLinkRequest.  # noqa: E501


        :return: The subject_type of this DirectLinkRequest.  # noqa: E501
        :rtype: ActionableSubjectTypeEnum
        """
        return self._subject_type

    @subject_type.setter
    def subject_type(self, subject_type):
        """Sets the subject_type of this DirectLinkRequest.


        :param subject_type: The subject_type of this DirectLinkRequest.  # noqa: E501
        :type: ActionableSubjectTypeEnum
        """

        self._subject_type = subject_type

    @property
    def allowed_actions(self):
        """Gets the allowed_actions of this DirectLinkRequest.  # noqa: E501


        :return: The allowed_actions of this DirectLinkRequest.  # noqa: E501
        :rtype: list[ChannelFunctionActionEnum]
        """
        return self._allowed_actions

    @allowed_actions.setter
    def allowed_actions(self, allowed_actions):
        """Sets the allowed_actions of this DirectLinkRequest.


        :param allowed_actions: The allowed_actions of this DirectLinkRequest.  # noqa: E501
        :type: list[ChannelFunctionActionEnum]
        """

        self._allowed_actions = allowed_actions

    @property
    def active_date_range(self):
        """Gets the active_date_range of this DirectLinkRequest.  # noqa: E501


        :return: The active_date_range of this DirectLinkRequest.  # noqa: E501
        :rtype: DirectLinkActiveDateRange
        """
        return self._active_date_range

    @active_date_range.setter
    def active_date_range(self, active_date_range):
        """Sets the active_date_range of this DirectLinkRequest.


        :param active_date_range: The active_date_range of this DirectLinkRequest.  # noqa: E501
        :type: DirectLinkActiveDateRange
        """

        self._active_date_range = active_date_range

    @property
    def executions_limit(self):
        """Gets the executions_limit of this DirectLinkRequest.  # noqa: E501


        :return: The executions_limit of this DirectLinkRequest.  # noqa: E501
        :rtype: int
        """
        return self._executions_limit

    @executions_limit.setter
    def executions_limit(self, executions_limit):
        """Sets the executions_limit of this DirectLinkRequest.


        :param executions_limit: The executions_limit of this DirectLinkRequest.  # noqa: E501
        :type: int
        """

        self._executions_limit = executions_limit

    @property
    def caption(self):
        """Gets the caption of this DirectLinkRequest.  # noqa: E501


        :return: The caption of this DirectLinkRequest.  # noqa: E501
        :rtype: str
        """
        return self._caption

    @caption.setter
    def caption(self, caption):
        """Sets the caption of this DirectLinkRequest.


        :param caption: The caption of this DirectLinkRequest.  # noqa: E501
        :type: str
        """

        self._caption = caption

    @property
    def enabled(self):
        """Gets the enabled of this DirectLinkRequest.  # noqa: E501


        :return: The enabled of this DirectLinkRequest.  # noqa: E501
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """Sets the enabled of this DirectLinkRequest.


        :param enabled: The enabled of this DirectLinkRequest.  # noqa: E501
        :type: bool
        """

        self._enabled = enabled

    @property
    def disable_http_get(self):
        """Gets the disable_http_get of this DirectLinkRequest.  # noqa: E501


        :return: The disable_http_get of this DirectLinkRequest.  # noqa: E501
        :rtype: bool
        """
        return self._disable_http_get

    @disable_http_get.setter
    def disable_http_get(self, disable_http_get):
        """Sets the disable_http_get of this DirectLinkRequest.


        :param disable_http_get: The disable_http_get of this DirectLinkRequest.  # noqa: E501
        :type: bool
        """

        self._disable_http_get = disable_http_get

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DirectLinkRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DirectLinkRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
