# coding: utf-8

"""
    SUPLA Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from swagger_client.models.schedule_future import ScheduleFuture  # noqa: F401,E501
from swagger_client.models.schedule_past import SchedulePast  # noqa: F401,E501


class ScheduleClosestExecutions(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'past': 'list[SchedulePast]',
        'future': 'list[ScheduleFuture]'
    }

    attribute_map = {
        'past': 'past',
        'future': 'future'
    }

    def __init__(self, past=None, future=None):  # noqa: E501
        """ScheduleClosestExecutions - a model defined in Swagger"""  # noqa: E501
        self._past = None
        self._future = None
        self.discriminator = None
        if past is not None:
            self.past = past
        if future is not None:
            self.future = future

    @property
    def past(self):
        """Gets the past of this ScheduleClosestExecutions.  # noqa: E501


        :return: The past of this ScheduleClosestExecutions.  # noqa: E501
        :rtype: list[SchedulePast]
        """
        return self._past

    @past.setter
    def past(self, past):
        """Sets the past of this ScheduleClosestExecutions.


        :param past: The past of this ScheduleClosestExecutions.  # noqa: E501
        :type: list[SchedulePast]
        """

        self._past = past

    @property
    def future(self):
        """Gets the future of this ScheduleClosestExecutions.  # noqa: E501


        :return: The future of this ScheduleClosestExecutions.  # noqa: E501
        :rtype: list[ScheduleFuture]
        """
        return self._future

    @future.setter
    def future(self, future):
        """Sets the future of this ScheduleClosestExecutions.


        :param future: The future of this ScheduleClosestExecutions.  # noqa: E501
        :type: list[ScheduleFuture]
        """

        self._future = future

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ScheduleClosestExecutions, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ScheduleClosestExecutions):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
