# coding: utf-8

"""
    SUPLA Cloud API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from swagger_client.models.channel import Channel  # noqa: F401,E501
from swagger_client.models.channel_function_action import ChannelFunctionAction  # noqa: F401,E501
from swagger_client.models.object import Object  # noqa: F401,E501
from swagger_client.models.schedule_closest_executions import ScheduleClosestExecutions  # noqa: F401,E501


class Schedule(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'time_expression': 'str',
        'action': 'ChannelFunctionAction',
        'action_param': 'Object',
        'mode': 'str',
        'date_start': 'datetime',
        'date_end': 'datetime',
        'enabled': 'bool',
        'caption': 'str',
        'retry': 'bool',
        'channel_id': 'int',
        'action_id': 'int',
        'channel': 'Channel',
        'closest_executions': 'list[ScheduleClosestExecutions]'
    }

    attribute_map = {
        'id': 'id',
        'time_expression': 'timeExpression',
        'action': 'action',
        'action_param': 'actionParam',
        'mode': 'mode',
        'date_start': 'dateStart',
        'date_end': 'dateEnd',
        'enabled': 'enabled',
        'caption': 'caption',
        'retry': 'retry',
        'channel_id': 'channelId',
        'action_id': 'actionId',
        'channel': 'channel',
        'closest_executions': 'closestExecutions'
    }

    def __init__(self, id=None, time_expression=None, action=None, action_param=None, mode=None, date_start=None, date_end=None, enabled=None, caption=None, retry=None, channel_id=None, action_id=None, channel=None, closest_executions=None):  # noqa: E501
        """Schedule - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._time_expression = None
        self._action = None
        self._action_param = None
        self._mode = None
        self._date_start = None
        self._date_end = None
        self._enabled = None
        self._caption = None
        self._retry = None
        self._channel_id = None
        self._action_id = None
        self._channel = None
        self._closest_executions = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if time_expression is not None:
            self.time_expression = time_expression
        if action is not None:
            self.action = action
        if action_param is not None:
            self.action_param = action_param
        if mode is not None:
            self.mode = mode
        if date_start is not None:
            self.date_start = date_start
        if date_end is not None:
            self.date_end = date_end
        if enabled is not None:
            self.enabled = enabled
        if caption is not None:
            self.caption = caption
        if retry is not None:
            self.retry = retry
        if channel_id is not None:
            self.channel_id = channel_id
        if action_id is not None:
            self.action_id = action_id
        if channel is not None:
            self.channel = channel
        if closest_executions is not None:
            self.closest_executions = closest_executions

    @property
    def id(self):
        """Gets the id of this Schedule.  # noqa: E501

        Schedule identifier  # noqa: E501

        :return: The id of this Schedule.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Schedule.

        Schedule identifier  # noqa: E501

        :param id: The id of this Schedule.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def time_expression(self):
        """Gets the time_expression of this Schedule.  # noqa: E501

        Schedule time expression in crontab notation (with some custom additions).  # noqa: E501

        :return: The time_expression of this Schedule.  # noqa: E501
        :rtype: str
        """
        return self._time_expression

    @time_expression.setter
    def time_expression(self, time_expression):
        """Sets the time_expression of this Schedule.

        Schedule time expression in crontab notation (with some custom additions).  # noqa: E501

        :param time_expression: The time_expression of this Schedule.  # noqa: E501
        :type: str
        """

        self._time_expression = time_expression

    @property
    def action(self):
        """Gets the action of this Schedule.  # noqa: E501


        :return: The action of this Schedule.  # noqa: E501
        :rtype: ChannelFunctionAction
        """
        return self._action

    @action.setter
    def action(self, action):
        """Sets the action of this Schedule.


        :param action: The action of this Schedule.  # noqa: E501
        :type: ChannelFunctionAction
        """

        self._action = action

    @property
    def action_param(self):
        """Gets the action_param of this Schedule.  # noqa: E501

        Depends on the action.  # noqa: E501

        :return: The action_param of this Schedule.  # noqa: E501
        :rtype: Object
        """
        return self._action_param

    @action_param.setter
    def action_param(self, action_param):
        """Sets the action_param of this Schedule.

        Depends on the action.  # noqa: E501

        :param action_param: The action_param of this Schedule.  # noqa: E501
        :type: Object
        """

        self._action_param = action_param

    @property
    def mode(self):
        """Gets the mode of this Schedule.  # noqa: E501


        :return: The mode of this Schedule.  # noqa: E501
        :rtype: str
        """
        return self._mode

    @mode.setter
    def mode(self, mode):
        """Sets the mode of this Schedule.


        :param mode: The mode of this Schedule.  # noqa: E501
        :type: str
        """
        allowed_values = ["minutely", "hourly", "daily", "once"]  # noqa: E501
        if mode not in allowed_values:
            raise ValueError(
                "Invalid value for `mode` ({0}), must be one of {1}"  # noqa: E501
                .format(mode, allowed_values)
            )

        self._mode = mode

    @property
    def date_start(self):
        """Gets the date_start of this Schedule.  # noqa: E501


        :return: The date_start of this Schedule.  # noqa: E501
        :rtype: datetime
        """
        return self._date_start

    @date_start.setter
    def date_start(self, date_start):
        """Sets the date_start of this Schedule.


        :param date_start: The date_start of this Schedule.  # noqa: E501
        :type: datetime
        """

        self._date_start = date_start

    @property
    def date_end(self):
        """Gets the date_end of this Schedule.  # noqa: E501


        :return: The date_end of this Schedule.  # noqa: E501
        :rtype: datetime
        """
        return self._date_end

    @date_end.setter
    def date_end(self, date_end):
        """Sets the date_end of this Schedule.


        :param date_end: The date_end of this Schedule.  # noqa: E501
        :type: datetime
        """

        self._date_end = date_end

    @property
    def enabled(self):
        """Gets the enabled of this Schedule.  # noqa: E501


        :return: The enabled of this Schedule.  # noqa: E501
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """Sets the enabled of this Schedule.


        :param enabled: The enabled of this Schedule.  # noqa: E501
        :type: bool
        """

        self._enabled = enabled

    @property
    def caption(self):
        """Gets the caption of this Schedule.  # noqa: E501


        :return: The caption of this Schedule.  # noqa: E501
        :rtype: str
        """
        return self._caption

    @caption.setter
    def caption(self, caption):
        """Sets the caption of this Schedule.


        :param caption: The caption of this Schedule.  # noqa: E501
        :type: str
        """

        self._caption = caption

    @property
    def retry(self):
        """Gets the retry of this Schedule.  # noqa: E501


        :return: The retry of this Schedule.  # noqa: E501
        :rtype: bool
        """
        return self._retry

    @retry.setter
    def retry(self, retry):
        """Sets the retry of this Schedule.


        :param retry: The retry of this Schedule.  # noqa: E501
        :type: bool
        """

        self._retry = retry

    @property
    def channel_id(self):
        """Gets the channel_id of this Schedule.  # noqa: E501


        :return: The channel_id of this Schedule.  # noqa: E501
        :rtype: int
        """
        return self._channel_id

    @channel_id.setter
    def channel_id(self, channel_id):
        """Sets the channel_id of this Schedule.


        :param channel_id: The channel_id of this Schedule.  # noqa: E501
        :type: int
        """

        self._channel_id = channel_id

    @property
    def action_id(self):
        """Gets the action_id of this Schedule.  # noqa: E501


        :return: The action_id of this Schedule.  # noqa: E501
        :rtype: int
        """
        return self._action_id

    @action_id.setter
    def action_id(self, action_id):
        """Sets the action_id of this Schedule.


        :param action_id: The action_id of this Schedule.  # noqa: E501
        :type: int
        """

        self._action_id = action_id

    @property
    def channel(self):
        """Gets the channel of this Schedule.  # noqa: E501


        :return: The channel of this Schedule.  # noqa: E501
        :rtype: Channel
        """
        return self._channel

    @channel.setter
    def channel(self, channel):
        """Sets the channel of this Schedule.


        :param channel: The channel of this Schedule.  # noqa: E501
        :type: Channel
        """

        self._channel = channel

    @property
    def closest_executions(self):
        """Gets the closest_executions of this Schedule.  # noqa: E501

        Returned only if requested by the `include` parameter. Contains two arrays of maximum 3 closest past and future executions.  # noqa: E501

        :return: The closest_executions of this Schedule.  # noqa: E501
        :rtype: list[ScheduleClosestExecutions]
        """
        return self._closest_executions

    @closest_executions.setter
    def closest_executions(self, closest_executions):
        """Sets the closest_executions of this Schedule.

        Returned only if requested by the `include` parameter. Contains two arrays of maximum 3 closest past and future executions.  # noqa: E501

        :param closest_executions: The closest_executions of this Schedule.  # noqa: E501
        :type: list[ScheduleClosestExecutions]
        """

        self._closest_executions = closest_executions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Schedule, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Schedule):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
